version: '3'
services:
  springboot-app:
    ports:
      - 8080:8080
    build:
      context: .
      args:
        JAR_FILE: /Cart-Service.jar
    restart: always

  cassandradb:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
  
  kafka-1:
    image: apache/kafka:3.7.0
    hostname: kafka-1
    container_name: walgreens-kafka-1
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_TOOLS_LOG4J_LOGLEVEL: DEBUG
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - kafka-net
  
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=root
    command: ["redis-server", "--requirepass", "root"]
    ports:
      - "6379:6379"
networks:
  kafka-net:
    driver: bridge